# Shell variables
# Generated by 'wal'
wallpaper='/home/flo/Pictures/wallpapers/wallpaper_5.jpg'

# Special
background='#121212'
foreground='#e2e3e3'
cursor='#e2e3e3'

# Colors
color0='#121212'
color1='#D17805'
color2='#F39004'
color3='#F39C13'
color4='#C19862'
color5='#798284'
color6='#A2A29F'
color7='#e2e3e3'
color8='#9e9e9e'
color9='#D17805'
color10='#F39004'
color11='#F39C13'
color12='#C19862'
color13='#798284'
color14='#A2A29F'
color15='#e2e3e3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
