import = [
"~/.config/alacritty/themes/catppuccin_macchiato.toml",
]

[font]
size = 11.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[keyboard]
bindings = [
  { key = "Enter", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "y", mods = "Control|Shift", action = "IncreaseFontSize" },
  { key = "i", mods = "Control|Shift", action = "DecreaseFontSize" },
  { key = "j", mods = "Control|Shift", action = "ResetFontSize" },

  { key = "s", mods = "Control|Shift", action = "ToggleViMode" },
  { key = "Escape", mode = "Vi|~Search", action = "ToggleViMode" },
  { key = "s", mode = "Vi|~Search", action = "ToggleNormalSelection" },
  { key = "x", mode = "Vi|~Search", action = "ToggleLineSelection" },
  { key = ";", mode = "Vi|~Search", action = "ClearSelection" },



  
]

[scrolling]
history = 50000

[window]
opacity = 0.8
