# starship.toml
# Folder : /home/.config/

palette = "catppuccin_macchiato"
add_newline = false

format = """
$username\
[](bg:bg_ip bg_user)\
$localip\
[](bg:bg_git bg_ip)\
$git_branch\
$git_status\
$git_metrics\
[](bg:bg_code bg_git)\
$rust\
$c\
$lua\
$python\
[](bg:bg_dir bg_code)\
$directory\
[](bg:bg_status bg_dir)\
$cmd_duration\
$status\
$jobs\
[ ](bg:bg_tranparent bg_status)\
"""

[username]
show_always = true
style_user = "bg:bg_user surface0 bold"
style_root = "bg:red surface0 bold"
format = '[ $user ]($style)'
disabled = false

[localip]
ssh_only = true
style = "bg:bg_ip base bold"
format = '[ @$localipv4 ]($style)'
disabled = false

[directory]
style = "bg:bg_dir base"
format = '[ $symbol($path) ]($style)'
truncation_length = 4
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
style = "bg:bg_git base"
symbol = " "
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:bg_git base bold"
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_metrics]
added_style = "base bg:bg_git"
deleted_style = "base bg:bg_git"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[rust]
style = "bg:bg_code red"
symbol = '⚙️ '
format = '[ $symbol($version) ]($style)'

[c]
style = "bg:bg_code blue"
symbol = " "
format = '[ $symbol($version(-$name)) ]($style)'
detect_extensions = ['c', 'h', 'cpp', 'cxx', 'cc']

[lua]
style = "bg:bg_code blue"
symbol = " "
format = '[ $symbol($version) ]($style)'

[python]
style = "bg:bg_code blue"
symbol = " "
format = '[ $symbol${pyenv_prefix}(${version}) [(\($virtualenv\) )](bg:bg_code yellow bold)]($style)'
detect_files = [
  '.python-version',
  'Pipfile',
  '__init__.py',
  'pyproject.toml',
  'requirements.txt',
  'setup.py',
] # Remove tox.ini

[cmd_duration]
style = "bg:bg_status yellow"
format = '[ ⏱ $duration ]($style)'

[status]
disabled = false
style = "bg:bg_status red bold"
format = '[ $symbol$status ]($style)'

[jobs]
style = "bg:bg_status peach bold"
format = '[ $symbol $number ]($style)'


[palettes.catppuccin_macchiato]
bg_user = "#8aadf4"
bg_ip = "#91b6ff"
bg_dir = "#a6da95"
bg_git = "#eed49f"
bg_code = "#494d64"
bg_status = "#363a4f"
bg_tranparent = "#FF000000"

rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
