# starship.toml
# Folder : /home/.config/

palette = "oneyellow"
add_newline = false

format = """
$username\
[](bg:bg_ip bg_user)\
$localip\
[](bg:bg_git bg_ip)\
$git_branch\
$git_status\
$git_metrics\
[](bg:bg_code bg_git)\
$rust\
$c\
$lua\
$python\
[](bg:bg_dir bg_code)\
$directory\
[](bg:bg_status bg_dir)\
$cmd_duration\
$status\
$jobs\
[ ](bg:bg_tranparent bg_status)\
"""

[username]
show_always = true
style_user = "bg:bg_user fg_user bold"
style_root = "bg:red fg_user bold"
format = '[ $user ]($style)'
disabled = false

[localip]
ssh_only = true
style = "bg:bg_ip fg_ip bold"
format = '[ @$localipv4 ]($style)'
disabled = false

[directory]
style = "bg:bg_dir fg_dir"
format = '[ $symbol($path) ]($style)'
truncation_length = 4
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
style = "bg:bg_git fg_git"
symbol = " "
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:bg_git fg_git bold"
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_metrics]
added_style = "bg:bg_git bg:bg_git fg_git"
deleted_style = "bg:bg_gitase bg:bg_git fg_git"
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
disabled = false

[rust]
style = "bg:bg_code fg_rust"
symbol = '󱘗 '
format = '[ $symbol($version) ]($style)'

[c]
style = "bg:bg_code fg_c"
symbol = " "
format = '[ $symbol($version(-$name)) ]($style)'
detect_extensions = ['c', 'h', 'cpp', 'cxx', 'cc']

[lua]
style = "bg:bg_code fg_lua"
symbol = " "
format = '[ $symbol($version) ]($style)'

[python]
style = "bg:bg_code fg_python"
symbol = " "
format = '[ $symbol${pyenv_prefix}(${version}) [(\($virtualenv\) )](bg:bg_code yellow bold)]($style)'
detect_files = [
  '.python-version',
  'Pipfile',
  '__init__.py',
  'pyproject.toml',
  'requirements.txt',
  'setup.py',
] # Remove tox.ini

[cmd_duration]
style = "bg:bg_status fg_duration"
format = '[ 󰔛 $duration ]($style)'

[status]
disabled = false
style = "bg:bg_status fg_status bold"
format = '[ $symbol$status ]($style)'

[jobs]
style = "bg:bg_status fg_job bold"
format = '[ $symbol $number ]($style)'

[palettes.gruvbox]
bg_user = "#458588"
bg_ip = "#83A598"
bg_dir = "#689D6A"
bg_git = "#D79921"
bg_code = "#1D2021"
bg_status = "#1D2021"
bg_tranparent = "#FF000000"

fg_user = "#282828"
fg_ip = "#282828"
fg_dir = "#282828"
fg_git = "#282828"
fg_rust = "#CC241D"
fg_c = "#458588"
fg_lua = "#458588"
fg_python = "#D79921"
fg_duration = "#EBDBB2"
fg_status = "#CC241D"

[palettes.gruvbox_light]
bg_user = "#458588"
bg_ip = "#83A598"
bg_dir = "#689D6A"
bg_git = "#D79921"
bg_code = "#EBDBB2"
bg_status = "#EBDBB2"
bg_tranparent = "#FF000000"

fg_user = "#3C3836"
fg_ip = "#3C3836"
fg_dir = "#3C3836"
fg_git = "#3C3836"
fg_rust = "#CC241D"
fg_c = "#458588"
fg_lua = "#458588"
fg_python = "#D79921"
fg_duration = "#3C3836"
fg_status = "#CC241D"

[palettes.onedark]
bg_user = "#62AEEF"
bg_ip = "#55B6C2"
bg_dir = "#98C379"
bg_git = "#E5C07A"
bg_code = "#1D2025"
bg_status = "#1D2025"
bg_tranparent = "#FF000000"

fg_user = "#282C33"
fg_ip = "#282C33"
fg_dir = "#282C33"
fg_git = "#282C33"
fg_rust = "#E06B74"
fg_c = "#62AEEF"
fg_lua = "#62AEEF"
fg_python = "#E5C07A"
fg_duration = "#E5C07A"
fg_status = "#E06B74"

[palettes.oneyellow]
bg_user = "#F47644"
bg_ip = "#F4B043"
bg_dir = "#F6C745"
bg_git = "#F5DC44"
bg_code = "#1D2025"
bg_status = "#1D2025"
bg_tranparent = "#FF000000"

fg_user = "#282C33"
fg_ip = "#282C33"
fg_dir = "#282C33"
fg_git = "#282C33"
fg_rust = "#E06B74"
fg_c = "#62AEEF"
fg_lua = "#62AEEF"
fg_python = "#E5C07A"
fg_duration = "#E5C07A"
fg_status = "#E06B74"

[palettes.onelight]
bg_user = "#4078F1"
bg_ip = "#E4564A"
bg_dir = "#51A04F"
bg_git = "#E5C07A"
bg_code = "#EEEEEE"
bg_status = "#EEEEEE"
bg_tranparent = "#FF000000"

fg_user = "#FAFAFA"
fg_ip = "#FAFAFA"
fg_dir = "#FAFAFA"
fg_git = "#FAFAFA"
fg_rust = "#CA1343"
fg_c = "#4078F1"
fg_lua = "#4078F1"
fg_python = "#C08400"
fg_duration = "#C08400"
fg_status = "#CA1343"
