#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/powermenu.rasi"

# Theme Elements
prompt="`hostname` (`echo $DESKTOP_SESSION`)"
mesg="Uptime : `uptime -p | sed -e 's/up //g'`"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
if [[ "$layout" == 'NO' ]]; then
	option_1=" Lock"
	option_2=" Shutdown"
	option_3=" Reboot"
	option_4=" Logout"
	option_5=" Suspend"
	option_6=" Hibernate"
else
	option_1=""
	option_2=""
	option_3=""
	option_4=""
	option_5=""
	option_6=""
fi

rofi_cmd() {
  rofi -dmenu \
  -p "$prompt" \
  -mesg "$mesg" \
  -markup-rows \
  -theme ${RASI} \
  -kb-row-up '' \
  -kb-mode-complete '' \
  -kb-row-select '' \
  -kb-mode-complete '' \
  -kb-remove-char-back '' \
  -kb-select-1 'Ctrl+l' \
  -kb-select-2 'Ctrl+p' \
  -kb-select-3 'Ctrl+r' \
  -kb-select-4 'Ctrl+o' \
  -kb-select-5 'Ctrl+s' \
  -kb-select-6 'Ctrl+h'
}

chosen="$(echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd)"
case ${chosen} in
    $option_1)
      notify-send 'lock'
      "$DIR"/scripts/lockscreen
      ;;
    $option_2)
      notify-send 'Shutdown'
      systemctl poweroff
      ;;
    $option_3)
      notify-send 'Reboot'
      systemctl reboot
      ;;
    $option_4)
      notify-send 'Logout'
      hyprctl dispatch exit 0
      ;;
    $option_5)
      notify-send 'Suspend'
      mpc -q pause && pulsemixer --mute && $DIR/scripts/lockscreen && systemctl suspend
      ;;
    $option_6)
      notify-send 'Hibernate'
      systemctl hibernate
      ;;
esac
