#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/flo/Pictures/wallpapers/wallpaper_5.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
