theme = "onedark"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
shell = ["zsh"]
true-color = true

bufferline = "multiple"
auto-format = true

cursorline = true
# cursorcolumn = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "separator", "file-name"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "|"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
esc = ["collapse_selection", "keep_primary_selection"]

l = "goto_next_buffer"
L = "goto_previous_buffer"

C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"

D = "kill_to_line_end"

"," = "repeat_last_motion"

[keys.normal.space]
b.d = ":buffer-close"
b.D = ":buffer-close-all"
