theme = "onedark"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
shell = ["zsh"]

true-color = true
color-modes = true

bufferline = "multiple"
auto-format = true

cursorline = true
# cursorcolumn = true


[editor.statusline]
left = ["mode", "separator", "file-name"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding"]

mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

separator = "  "


[editor.cursor-shape]
insert = "bar"
# normal = "block"
select = "underline"

[editor.file-picker]
hidden = false


# or control each character
[editor.whitespace.render]
# space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
tab = "→"
newline = "↵"
tabpad = "·"  # Tabs will look like "→···" (depending on tab width)


[keys.normal]
# C-p = ["move_line_up", "scroll_up"]
# C-n = ["move_line_down", "scroll_down"]

# esc = ["collapse_selection", "keep_primary_selection"]

h = "goto_next_buffer"
H = "goto_previous_buffer"

C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"

D = "kill_to_line_end"

# "," = "repeat_last_motion"

A-c = "copy_selection_on_prev_line"

s = "select_mode"
v = "select_regex"
V = "split_selection"


# o = "extend_to_line_start"
# "^" = "extend_to_first_nonwhitespace"
# "$" = "extend_to_line_end"

[keys.select]
# "," = "repeat_last_motion"
s = "select_mode"
v = "select_regex"
V = "split_selection"

[keys.normal.space]
# b.b = "buffer_picker"
B = "buffer_picker"
b.d = ":buffer-close"
b.D = ":buffer-close-all"
w = "no_op"

[keys.normal.g]
n = "goto_first_nonwhitespace"
# t = "goto_line_start"
p = "goto_line_end"
# l = "goto_window_center"

[keys.select.g]
n = "goto_first_nonwhitespace"
# t = "goto_line_start"
p = "goto_line_end"
# l = "goto_window_center"

[keys.normal."C-w"]
# [keys.normal.space.w]
h = "hsplit"

H = "no_op"
K = "no_op"
J = "no_op"
L = "no_op"

# h = "no_op"
k = "no_op"
j = "no_op"
l = "no_op"

C-h = "no_op"
C-k = "no_op"
C-j = "no_op"
C-l = "no_op"

C-left = "swap_view_left"
C-down = "swap_view_down"
C-up = "swap_view_up"
C-right = "swap_view_right"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

