#!/usr/bin/env bash

COLOR=$(grim -g "$(slurp -p)" -t ppm - | magick - -format '%[pixel:p{0,0}]' txt:- | awk -F ' ' 'NR==2 {print $3}')

wl-copy "${COLOR#\#}"
echo "$COLOR"
notify-send -t 8000 "${COLOR} copied."
