#!/usr/bin/env bash

if [[ -n $(expressvpn status | grep "Connecting...") ]]; then
  TXT="Connecting..."
elif [[ -z $(expressvpn status | grep --fixed-strings "Not connected") ]]; then
  TXT=$(expressvpn status | grep --fixed-strings "Connected to" | cut --delimiter=" " --field=3-5)
else
  TXT=""
fi

echo "  $TXT"
