#!/usr/bin/env bash
# florent@linguenheld.fr 2025

usage() {
  echo "Usage: $(basename "${0}") TITLE APPNAME"
  echo
  echo "   Focus a window in the Niri WM."
  echo "   List all opened windows which contain TITLE and the exact APPNAME."
  echo "   (the current focused window is ignored)"
  echo "   If there are more than one, ask user to choose one with fuzzel."
  echo
  echo "Example: $(basename "${0}") wordreference firefox"
  echo
  echo "   -h to display this message."
}

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  usage
  exit 0
elif [[ -z "$1" || -z "$1" || "$1" == "-h" ]]; then
  usage
  exit 1
fi

# ----------
LIST=$(niri msg windows | grep --ignore-case --before-context 1 --after-contex 1 -E "^  Title: .*$1.*" \
                        | grep --ignore-case --before-context 2 -E "^  App ID: \"$2\"" \
                        | grep --ignore-case --after-contex 1 -E "^Window ID" \
                        | sed 's/^--//' \
                        | paste -sd ' ' \
                        | sed 's/Window ID//' \
                        | sed 's/Window ID/\\n/g' )

if [[ -z "$LIST" ]]; then
  notify-send --urgency=low "'$1' on '$2' not found"
  exit 0

else
  LIST=$(echo -e "$LIST" | sed 's/:   Title: / -> /' \
                         | sed '/: (focused)   Title: /d' \
                         | sed 's/^[[:space:]]*//' \
                         | sed 's/[[:space:]]*$//' )

  if [[ -z "$LIST" ]]; then
    notify-send --urgency=low "'$1' is already focused"
    exit 0

  elif [[ $(echo -e "$LIST" | wc -l) == "1" ]]; then
      ID=$(echo -e "$LIST" | head -n 1 | awk -F ' -> ' '{print $1}' )

  else
      CHOICE=$(echo -e "$LIST" | fuzzel --dmenu \
                                        --placeholder " Which window ?" \
                                        --lines "$(echo -e "$LIST" | wc -l)" )

      if [[ -n "$CHOICE" ]]; then
        ID=$(echo -e "$CHOICE" | head -n 1 | awk -F ' -> ' '{print $1}')
      else
        exit 0
      fi
  fi

  niri msg action focus-window --id "$ID" 
fi
