#!/usr/bin/env bash

kill -9 "$(pgrep swaybg)"
swaybg -i "$HOME/.config/niri/wallpapers/catppuccin_frappe.jpg" &

kill -9 "$(pgrep swayidle)"
swayidle -w timeout 601 'niri msg action power-off-monitors' timeout 600 'swaylock -f -c 282828' before-sleep 'swaylock -f -c 282828' &
# swayidle -w timeout 31 'niri msg action power-off-monitors' timeout 30 'swaylock -f -c 282828' before-sleep 'swaylock -f -c 282828'

CONFIG="$HOME/.config/niri/waybar/config"
STYLE="$HOME/.config/niri/waybar/style.css"
kill -9 "$(pgrep waybar)"
waybar --bar main-bar --log-level error --config "${CONFIG}" --style "${STYLE}" &
