#!/usr/bin/env bash

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
  if [[ $(pidof "${_prs}") ]]; then
    kill -9 "$(pidof "${_prs}")"
  fi
done

# Set wallpaper
~/.config/hypr/scripts/wallpaper &

# Lauch notification daemon (mako)
~/.config/hypr/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/hypr/scripts/statusbar &

# Start network manager applet
# nm-applet --indicator &

# Start mpd
# exec mpd &
