#!/usr/bin/env bash

## launch waybar with alt config
CONFIG="$HOME/.config/niri/waybar/config"
STYLE="$HOME/.config/niri/waybar/style.css"

waybar --bar main-bar --log-level error --config "${CONFIG}" --style "${STYLE}"
