#!/usr/bin/env bash
# Florent Linguenheld 2025

NIRI_FOLDER="$HOME/.config/niri"
NIRI_STYLE_FILE="$NIRI_FOLDER/config/style.kdl"
NIRI_REG_ACTIVE=" active-gradient .*"
NIRI_REG_INACTIVE=" inactive-gradient .*"

SWAYBG_FILE="$NIRI_FOLDER/scripts/startup"
SWAYBG_REG="papers/.*\.jpg"

WAYBAR_FILE="$NIRI_FOLDER/waybar/style.css"
WAYBAR_REG="@import .*\.css\";"

MAKO_FOLDER="$HOME/.config/mako/"
MAKO_FOLDER_THEMES="$MAKO_FOLDER/themes/"

ALACRITTY_FILE="$HOME/.config/alacritty/alacritty.toml"
ALACRITTY_REG="themes/.*\.toml"

HELIX_FILE="$HOME/.config/helix/config.toml"
HELIX_REG="theme = \".*\""

STARSHIP_FILE="$HOME/.config/starship.toml"
STARSHIP_REG="palette = \".*\""

FUZZEL_FILE="$HOME/.config/fuzzel/fuzzel.ini"
FUZZEL_REG="include = ~/.config/fuzzel/themes/.*"

# Menu
case $(echo -e "gruvbox\ngruvbox light\none dark\none yellow\none light\ncatppuccin latte\ncatppuccin mocha" | fuzzel --dmenu \
                                                                                                                      --font "JetBrains Mono:size=25" \
                                                                                                                      --lines 7 \
                                                                                                                      --width 25 \
                                                                                                                      --line-height 50 \
                                                                                                                      --inner-pad 50 \
                                                                                                                      --placeholder " Theme selection") in

  "one dark")
    NEW="onedark"
    NEW_HELIX="onedark"
    NEW_ALACRITTY="onedark"
    NEW_NIRI_ACTIVE=" active-gradient from=\"#61AFEF\" to=\"#528BFF\""
    NEW_NIRI_INACTIVE=" inactive-gradient from=\"#252932\" to=\"#1D2025\""
    darkman set dark
  ;;
  "one yellow")
    NEW="oneyellow"
    NEW_HELIX="onedark"
    NEW_ALACRITTY="onedark"
    NEW_NIRI_ACTIVE=" active-gradient from=\"#EAA32F\" to=\"#EB642F\""
    NEW_NIRI_INACTIVE=" inactive-gradient from=\"#252932\" to=\"#1D2025\""
    darkman set dark
  ;;
  "one light")
    NEW="onelight"
    NEW_HELIX="onelight"
    NEW_ALACRITTY="onelight"
    NEW_NIRI_ACTIVE=" active-gradient from=\"#A626A4\" to=\"#4078F2\""
    NEW_NIRI_INACTIVE=" inactive-gradient from=\"#A1A1A1\" to=\"#CFD0D2\""
    darkman set light
  ;;
  "gruvbox")
    NEW="gruvbox"
    NEW_HELIX="gruvbox"
    NEW_ALACRITTY="gruvbox"
    NEW_NIRI_ACTIVE=" active-gradient from=\"#458588\" to=\"#689D6A\""
    NEW_NIRI_INACTIVE=" inactive-gradient from=\"#928374\" to=\"#282828\""
    darkman set dark
  ;;
  "gruvbox light")
    NEW="gruvbox_light"
    NEW_HELIX="gruvbox_light"
    NEW_ALACRITTY="gruvbox_light"
    NEW_NIRI_ACTIVE=" active-gradient from=\"#458588\" to=\"#689D6A\""
    NEW_NIRI_INACTIVE=" inactive-gradient from=\"#928374\" to=\"#282828\""
    darkman set light
  ;;
  "catppuccin latte")
    NEW="catppuccin_latte"
    NEW_HELIX="catppuccin_latte"
    NEW_ALACRITTY="catppuccin_latte"
    NEW_NIRI_ACTIVE=" active-gradient from=\"#1e66f5\" to=\"#04a5e5\""
    NEW_NIRI_INACTIVE=" inactive-gradient from=\"#7c7f93\" to=\"#9ca0b0\""
    darkman set light
  ;;
  "catppuccin mocha")
    NEW="catppuccin_mocha"
    NEW_HELIX="catppuccin_mocha"
    NEW_ALACRITTY="catppuccin_mocha"
    NEW_NIRI_ACTIVE=" active-gradient from=\"#89b4fa\" to=\"#89dceb\""
    NEW_NIRI_INACTIVE=" inactive-gradient from=\"#9399b2\" to=\"#6c7086\""
    darkman set dark
  ;;
  *)
    echo "wrong"
    exit 0
  ;;

esac

# Apply
sed -i "s%${NIRI_REG_ACTIVE}%${NEW_NIRI_ACTIVE}%" "${NIRI_STYLE_FILE}"
sed -i "s%${NIRI_REG_INACTIVE}%${NEW_NIRI_INACTIVE}%" "${NIRI_STYLE_FILE}"

sed -i "s#${WAYBAR_REG}#@import \".\/themes/${NEW}.css\";#" "${WAYBAR_FILE}"
cp "${MAKO_FOLDER_THEMES}${NEW}" "${MAKO_FOLDER}config" && makoctl reload
sed -i "s#${ALACRITTY_REG}#themes/${NEW_ALACRITTY}.toml#" "${ALACRITTY_FILE}"
sed -i "s#${FUZZEL_REG}#include = ~/.config/fuzzel/themes/${NEW}.ini#" "${FUZZEL_FILE}"
sed -i "s#${HELIX_REG}#theme = \"${NEW_HELIX}\"#" "${HELIX_FILE}" && pkill -USR1 hx 2> /dev/null
sed -i "s#${STARSHIP_REG}#palette = \"${NEW}\"#" "${STARSHIP_FILE}"
sed -i "s#${SWAYBG_REG}#\papers/${NEW}.jpg#" "${SWAYBG_FILE}"

"${NIRI_FOLDER}/scripts/combine_niri_config"
"${NIRI_FOLDER}/scripts/startup" &
