#!/bin/bash

TXT=$(expressvpn status | grep --fixed-strings "Not connected")

if [[ -z $TXT ]]
then
  TXT=$(expressvpn status | grep --fixed-strings "Connected to" | cut --delimiter=" " --field=3-5)
fi

if [[ -z $TXT ]]
then
  TXT="VPN ..."
fi

echo "$TXT"
