#!/usr/bin/env bash

LIST=$1
CURRENT=$2
TITLE=$3

if [[ -n $4 ]]; then
  THEME="${HOME}/.config/hypr/rofi/${4}.rasi"
else
  THEME="${HOME}/.config/hypr/rofi/base.rasi"
fi

echo -e "${LIST%\\n}" | sed "s/^${CURRENT}$/   >>> ${CURRENT} <<<  /" | rofi -dmenu -theme "$THEME" -no-custom -mesg "${TITLE}"
