#!/usr/bin/env bash

# Import Current Theme
DIR="$HOME/.config/hypr"
RASI="$DIR/rofi/powermenu.rasi"

mesg="${USER} : $(uptime | awk '{print $3}' | awk -F ',' '{print $1}' | sed 's/:/ h /')"

# Options
layout=`cat ${RASI} | grep 'USE_ICON' | cut -d'=' -f2`
	option_1="󰌾 <b>(L)</b>ock"
	option_2="⏻ <b>(P)</b>ower off"
	option_3=" <b>(R)</b>eboot"
	option_4="󰍃 Log<b>(O)</b>ut"
	option_5="󰒲 <b>(S)</b>uspend"
	option_6=" <b>(H)</b>ibernate"

rofi_cmd() {
  rofi -dmenu \
  -mesg "$mesg" \
  -markup-rows \
  -theme ${RASI} \
  -i \
  -kb-row-up 'Up' \
  -kb-mode-complete '' \
  -kb-row-select '' \
  -kb-mode-complete '' \
  -kb-remove-char-back '' \
  -kb-select-1 'Ctrl+l' \
  -kb-select-2 'Ctrl+p' \
  -kb-select-3 'Ctrl+r' \
  -kb-select-4 'Ctrl+o' \
  -kb-select-5 'Ctrl+s' \
  -kb-select-6 'Ctrl+h'
}

chosen="$(echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5\n$option_6" | rofi_cmd)"
case ${chosen} in
    $option_1)
      notify-send 'lock'
      "$DIR"/scripts/lockscreen
      ;;
    $option_2)
      notify-send 'Shutdown'
      systemctl poweroff
      ;;
    $option_3)
      notify-send 'Reboot'
      systemctl reboot
      ;;
    $option_4)
      notify-send 'Logout'
      hyprctl dispatch exit 0
      ;;
    $option_5)
      notify-send 'Suspend'
      mpc -q pause && pulsemixer --mute && $DIR/scripts/lockscreen && systemctl suspend
      ;;
    $option_6)
      notify-send 'Hibernate'
      systemctl hibernate
      ;;
esac
