#!/usr/bin/env bash
# Florent Linguenheld 2024
HYPRLAND_FOLDER="$HOME/.config/hypr"
HYPRLAND_FILE="$HYPRLAND_FOLDER/hyprland.conf"
HYPRLAND_REG="source = ~/\.config/hypr/themes/.*\.conf"

WAYBAR_FILE="$HYPRLAND_FOLDER/waybar/style.css"
WAYBAR_REG="@import .*\.css\";"

ROFI_FILES="$HYPRLAND_FOLDER/rofi/"
ROFI_REG="themes/.*\.rasi"

MAKO_FOLDER="$HOME/.config/mako/"
MAKO_FOLDER_THEMES="$MAKO_FOLDER/themes/"

ALACRITTY_FILE="$HOME/.config/alacritty/alacritty.toml"
ALACRITTY_REG="themes/.*\.toml"

HELIX_FILE="$HOME/.config/helix/config.toml"
HELIX_REG="theme = \".*\""

STARSHIP_FILE="$HOME/.config/starship.toml"
STARSHIP_REG="palette = \".*\""

LIST="catppuccin\none dark\none light"

# Menu
CHOICE=$(~/.config/hypr/scripts/rofi_menu "$LIST" "" "New theme")
# CHOICE="one dark"
case "$CHOICE" in

  "catppuccin")
    NEW="catppuccin"
    echo "catppuccin"
  ;;
  "one dark")
    NEW="onedark"
    echo "one_dark"
  ;;
  "one light")
    NEW="onelight"
    echo "one_light"
  ;;
  *)
    echo "wrong"
    exit 0
  ;;

esac

# Apply
sed -i "s#${HYPRLAND_REG}#source = ~/\.config/hypr/themes/${NEW}\.conf#" "${HYPRLAND_FILE}"
sed -i "s#${WAYBAR_REG}#@import \".\/themes/${NEW}.css\";#" "${WAYBAR_FILE}" && "${HYPRLAND_FOLDER}/scripts/startup"
find "${ROFI_FILES}" -name "*.rasi" -exec sed -i "s#${ROFI_REG}#themes/${NEW}\.rasi#" {} \;
cp "${MAKO_FOLDER_THEMES}${NEW}" "${MAKO_FOLDER}config" && makoctl reload
sed -i "s#${ALACRITTY_REG}#themes/${NEW}.toml#" "${ALACRITTY_FILE}"
sed -i "s#${HELIX_REG}#theme = \"${NEW}\"#" "${HELIX_FILE}" && pkill -USR1 hx 2> /dev/null
sed -i "s#${STARSHIP_REG}#palette = \"${NEW}\"#" "${STARSHIP_FILE}"
