#!/usr/bin/env bash
# florent@linguenheld.fr 2024

THEMES="onedark,onedarker,onelight,everforest_light,pop-dark,"
HELIX_FILE="${HOME}/.config/helix/config.toml"

# ---------------------------------------------------------------------------------------
usage() {
  echo
  echo "Usage: $(basename "${0}") [-p]"
  echo "    Update the theme name in the '${HELIX_FILE} file"
  echo "    with the next theme in the list."
  echo
  echo "       -l LIST:        display the theme list."
  echo "       -m MENU:        Use rofi to select the next theme."
  echo "       -p PREVIOUS:    to set the previous theme."
  echo "       -h HELP:        display this message."
}

MODE="next"
while getopts plhm OPTION; do

  case ${OPTION} in

    m)
      MODE="menu"
    ;;
    l)
      MODE="list"
    ;;
    p)
      MODE="previous"
    ;;
    h)
      usage
      exit 0
    ;;
    ?)
      usage
      exit 1
    ;;
  esac
done

# ---------------------------------------------------------------------------------------
CURRENT=$(grep '^theme = ' "${HELIX_FILE}" | cut -d '"' -f2)

if [[ $MODE == "list" ]]; then
  echo "Themes: ${THEMES//,/, }"
  echo "Current: ${CURRENT}"
  exit
fi

if [[ $MODE == "previous" ]]; then
  THEMES=$(echo -e $THEMES | tac --separator , )
fi

if [[ $MODE == "previous" || $MODE == "next" ]]; then
  NEW=$(echo -e "${THEMES}" | awk -F "${CURRENT}," '{print $2}' | awk -F ','  '{print $1}')

  # Take the first if current was the last
  if [[ -z $NEW ]]; then
    NEW=$(echo -e "${THEMES}" | cut -d ',' -f 1)
  fi

  notify-send "✨ Helix: ${NEW} ✨"

elif [[ $MODE == "menu" ]]; then
  NEW=$("$HOME/.config/helix/scripts/rofi_menu" "${THEMES//,/\\n}" "$CURRENT" "Helix new theme")

  if [[ -z $NEW ]]; then
    exit 0
  else
    NEW="${NEW//[> <]/}"
  fi
fi

# ---------------------------------------------------------------------------------------
echo "From '${CURRENT}' to '${NEW}'"
if [[ -z $CURRENT ]]; then
  sed -i "1itheme = \"${NEW}\"" "${HELIX_FILE}"
else
  sed -i "s/theme = .*/theme = \"${NEW}\"/" "${HELIX_FILE}"
fi

# ---------------------------------------------------------------------------------------
# pkill -USR1 helix 2> /dev/null
pkill -USR1 hx 2> /dev/null

exit 0
