#!/usr/bin/env bash
# Folder : /home/bin/
# Florent Linguenheld 2024

FOLDER="${HOME}/.config/alacritty/"
FOLDER_THEMES="${FOLDER}themes/"
ALACRITTY_FILE="${FOLDER}alacritty.toml"

# ---------------------------------------------------------------------------------------
usage() {
  echo
  echo "Usage: $(basename "${0}") [-m] | [-p] | [-h]"
  echo "    Update the theme name in the '${ALACRITTY_FILE} file"
  echo "    with the next theme file name."
  echo "    Themes files have to be put here: '${FOLDER_THEMES}'"
  echo
  echo "       -m MENU:        select the new theme with rofi."
  echo "       -p PREVIOUS:    to set the previous theme."
  echo "       -h HELP:        display this message."
}

MODE="next"
while getopts phm OPTION; do

  case ${OPTION} in

    m)
      MODE="menu"
    ;;
    p)
      MODE="previous"
    ;;
    h)
      usage
      exit 0
    ;;
    ?)
      usage
      exit 1
    ;;
  esac
done

# ---------------------------------------------------------------------------------------
CURRENT=$(grep "themes" "${ALACRITTY_FILE}"  | awk -F '[/|"]' '{print $6}' | sed 's/.toml//')
THEMES=$(find "${FOLDER_THEMES}" -name "*.toml" -printf "%f\n" | sed 's/.toml//')

if [[ $MODE == "previous" ]]; then
  THEMES=$(echo -e "${THEMES}" | sort --reverse)
else
  THEMES=$(echo -e "${THEMES}" | sort)
fi

if [[ $MODE == "menu" ]]; then
    NEW=$(~/bin/rofi_menu "${THEMES}" "${CURRENT}" "Alacritty new theme")
    if [[ -z $NEW ]]; then
      exit 0
    fi

else
  NEW=$(echo -e "${THEMES}" | paste -s | awk -F "${CURRENT}" '{print $2}' | awk '{print $1}')
  if [[ -z $NEW ]]; then
    NEW=$(echo -e "${THEMES}" | head -1)
  fi
  notify-send "✨ Alacritty: ${NEW} ✨ "
fi

# ---------------------------------------------------------------------------------------
echo "From '${CURRENT%.toml}' to '${NEW%.toml}'"
sed -i "s/${CURRENT}.toml/${NEW}.toml/" "${ALACRITTY_FILE}"

exit 0
