#!/bin/bash
# Folder : /home/bin/

LIST=$1
CURRENT=$2
TITLE=$3

echo -e "${LIST%\\n}" | sed "s/^${CURRENT}$/   >>> ${CURRENT} <<<  /" | rofi -dmenu -theme "${HOME}/.config/hypr/rofi/flo.rasi" -no-custom -mesg "${TITLE}"
