#!/usr/bin/env bash
# Folder : /home/bin/

LIST=$1
CURRENT=$2
TITLE=$3

CONFIG="${HOME}/.config/hypr/rofi/flo.rasi"

if [[ -f "$CONFIG" ]]; then
  echo -e "${LIST%\\n}" | sed "s/^${CURRENT}$/   >>> ${CURRENT} <<<  /" | rofi -dmenu -theme "$CONFIG" -no-custom -mesg "${TITLE}"
else
  echo -e "${LIST%\\n}" | sed "s/^${CURRENT}$/   >>> ${CURRENT} <<<  /" | rofi -dmenu -no-custom -mesg "${TITLE}"
fi
