# starship.toml
# Folder : /home/.config/

palette = "catppuccin_macchiato"
add_newline = false

format = """
[❱](surface0)[❱](surface1)\
$username\
$localip\
$directory\
$git_branch\
$git_status\
$c\
$lua\
$python\
$cmd_duration\
$status\
[ ❱](overlay0)[❱ ](overlay1)
"""


[username]
show_always = true
style_user = "blue bold"
style_root = "red bold"
format = ' [$user]($style)'
disabled = false

[localip]
ssh_only = true
style = "red bold"
format = ' [❱](surface1) [@$localipv4]($style)'
disabled = false

[directory]
style = "green bold"
format = ' [❱](surface1) [$symbol($path)]($style)'
truncation_length = 4
fish_style_pwd_dir_length = 1
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
style = "peach bold"
symbol = " "
format = ' [❱](surface1) [$symbol$branch]($style)'

[git_status]
style = "peach bold"
format = '([ \[$all_status$ahead_behind\]]($style))'

[c]
style = "blue bold"
symbol = " "
format = ' [❱](surface2) [$symbol($version(-$name))]($style)'
detect_extensions = ['c', 'h', 'cpp', 'cxx', 'cc']

[lua]
style = "blue bold"
symbol = " "
format = ' [❱](surface2) [$symbol($version)]($style)'

[python]
style = "blue bold"
symbol = " "
format = ' [❱](surface2) [$symbol${pyenv_prefix}(${version})[( \($virtualenv\))](yellow bold)]($style)'
detect_files = ['.python-version', 'Pipfile', '__init__.py', 'pyproject.toml', 'requirements.txt', 'setup.py'] # Remove tox.ini

[cmd_duration]
style = "yellow bold"
format = ' [❱](overlay0) [⏱ $duration]($style)'

[status]
disabled = false
style = "red bold"
format = ' [❱](overlay0) [$symbol$status]($style)'


[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
