# starship.toml
# Folder : ~/.config/starship.toml

# palette = "catppuccin_frappe"
palette = "catppuccin_macchiato"

format = """
$os\
$username\
[](bg:green fg:sapphire)\
$directory\
[](bg:peach fg:green)\
$git_branch\
$git_status\
[](bg:yellow fg:peach)\
$c\
$lua\
$python\
[](bg:lavender fg:yellow)\
$status\
[ ](fg:lavender)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

[username]
show_always = true
style_user = "bg:sapphire fg:surface2"
style_root = "bg:sapphire fg:red bold"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:green fg:surface2"
format = '[ $symbol($path) ]($style)'
truncation_length = 6
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
style = "bg:peach fg:surface2"
symbol = " "
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:peach fg:surface1 bold"
format = '([\[$all_status$ahead_behind\] ]($style))'

[c]
style = "bg:yellow fg:surface2"
symbol = " "
format = '[ $symbol($version(-$name)) ]($style)'

[lua]
style = "bg:yellow fg:surface2"
symbol = " "
format = '[ $symbol($version) ]($style)'

[python]
style = "bg:yellow fg:surface2"
symbol = " "
format = '[ $symbol${pyenv_prefix}(${version}) [(\($virtualenv\))](bg:yellow fg:surface1 bold) ]($style)'

[status]
style = "bg:lavender fg:surface2"
format = '[ $symbol$status ]($style)'
disabled = false

# [cmd_duration]
# style = "bg:blue fg:surface2"
# format = '[ ⏱ $duration ]($style)'


[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
